# Generated by Django 4.0.4 on 2022-05-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('veg', 'vegeterian'), ('non-veg', 'non- vegetrian')], max_length=64)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
    ]
