# Generated by Django 4.0.4 on 2022-05-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chotaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pic',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='pro_images/'),
        ),
    ]
