# Generated by Django 4.0.4 on 2022-05-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chotaapp', '0009_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=False, max_length=150, null=True),
        ),
    ]
