# Generated by Django 4.0.4 on 2022-05-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chotaapp', '0011_alter_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='add',
            new_name='address',
        ),
    ]
